### ISSUE TITLE
[Fabric 1.21.1] Fishing lines still connect to other players in 1.6.2

### ISSUE THREAD

**Issue by revsorath** [Lightning-64/Tide#96]
**Game Version:** Minecraft 1.21.1
**Mod Loader:** Fabric

**Issue description**
There is [an issue for this already](https://github.com/Lightning-64/Tide/issues/16), and it's supposedly fixed in Tide 1.6, but we're having the same problem in Tide 1.6.2. 

**To Reproduce**
Have more than 1 player fishing.

**Additional context (optional)**
Disabling Tide's recolor for the fishing line doesn't change anything.

**Screenshots (optional)**

<img width="1920" height="892" alt="Image" src="https://github.com/user-attachments/assets/51f2bdf1-15bb-4bdd-b28e-23385a30bce7" />

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/0a43f432-d57f-42e0-b1a2-b384ac03cb16" />

**Comment by Lightning-64** [comment]
Yeah, I'm aware of this. I thought I fixed it because I made some changes to the rendering and the lines never connected for me, but it turned out to be an issue with Iris. I've asked the developers why this might be happening but no one has gotten back to me yet. I'll comment here if I come up with a solution!

**Comment by Fyoncle** [comment]
@Lightning-64 Also on 1.20.1

**Comment by Lightning-64** [comment]
Will be fixed in Tide 2.0

**Comment by Fyoncle** [comment]
> Will be fixed in Tide 2.0

Real question is will Tide 2.0 be for 1.20.1? Most devs hate on 1.20.1 recently since it's "old"

I will use Tide in my modpack and wouldn't be nice to have such a bug

**Comment by Lightning-64** [comment]
> > Will be fixed in Tide 2.0
> 
> Real question is will Tide 2.0 be for 1.20.1? Most devs hate on 1.20.1 recently since it's "old"
> 
> I will use Tide in my modpack and wouldn't be nice to have such a bug

yes. Tide 1.20.1 will keep being updated for the forseeable future.

**Comment by Fyoncle** [comment]
> > > Will be fixed in Tide 2.0
> > 
> > 
> > Real question is will Tide 2.0 be for 1.20.1? Most devs hate on 1.20.1 recently since it's "old"
> > I will use Tide in my modpack and wouldn't be nice to have such a bug
> 
> yes. Tide 1.20.1 will keep being updated for the forseeable future.

Awesome!! I wanna release my modpack's new update very soon and I have changed everything else to fit along Tide since it's an awesome mod but this bug is really annoying, is there any ETA? Should I wait for your release? My deadline would be around a month would it be out by then or should I just release as it is

**Comment by Lightning-64** [comment]
I can probably include this in the next patch update to Tide as well, which would come considerably sooner than the 2.0 update. I’d estimate sometime within the next two weeks.

**Comment by Fyoncle** [comment]
> I can probably include this in the next patch update to Tide as well, which would come considerably sooner than the 2.0 update. I’d estimate sometime within the next two weeks.

Thank you! What else does 2.0 update add by the way? It got me curious.

**Comment by Lightning-64** [comment]
> Thank you! What else does 2.0 update add by the way? It got me curious.

I've posted some info about the update in one of the discussion threads in Tide's discord server, I would check that out if you're interested.

**Comment by Lightning-64** [comment]
Fixed as of Tide 1.6.4

**Comment by Apollonu** [comment]
<img width="1920" height="1012" alt="Image" src="https://github.com/user-attachments/assets/5d91f853-64e5-4bb4-96d3-9a9f010a979e" />

<img width="1920" height="1012" alt="Image" src="https://github.com/user-attachments/assets/63bc912d-e666-45a7-8f74-d2ae213dc40e" />

Im still having the issue on a hosted forge 1.20.1 server

**Comment by Lightning-64** [comment]
> I'm still having the issue on a hosted forge 1.20.1 server

no way
Just to confirm, do you have Iris installed?

**Comment by Apollonu** [comment]
> > I'm still having the issue on a hosted forge 1.20.1 server
> 
> no way Just to confirm, do you have Iris installed?

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/43b878dd-f0c0-4207-8020-3fcc8f850c7a" />

**Comment by Apollonu** [comment]
I do not know if it still happens on online lan like world host for example.

**Comment by Lightning-64** [comment]
oh, I see. I have it only activating the fix if specifically Iris is installed, and not Oculus (even though they have the same functionality).
It should be an easy fix, I'll see if I can put out another file for forge 1.20.1 that finally resolves this issue completely
